var F=null,D=null,R="",fid=null;
var COLS=[{k:"seq",t:"序号",w:45,s:0},{k:"name",t:"项目名称",w:110,s:1},{k:"content",t:"项目内容",w:140,ta:1},{k:"investment",t:"投资额(万元)",w:75},{k:"economicBenefit",t:"经济效益(万元)",w:75},{k:"electricitySaving",t:"节电(万kWh)",w:72},{k:"coalSaving",t:"折标煤(t)",w:68},{k:"co2Reduction",t:"CO2(t)",w:62},{k:"materialSaving",t:"原辅料(t)",w:68},{k:"waterSaving",t:"节水(t)",w:62},{k:"codcrReduction",t:"COD(t)",w:62},{k:"ammoniaReduction",t:"氨氮(t)",w:58},{k:"smokeReduction",t:"烟尘(t)",w:58},{k:"dustReduction",t:"粉尘(t)",w:58},{k:"so2Reduction",t:"SO2(t)",w:58},{k:"noxReduction",t:"NOx(t)",w:58},{k:"vocReduction",t:"VOC(t)",w:58},{k:"solidWasteReduction",t:"固废(t)",w:58},{k:"liquidWasteReduction",t:"废液(t)",w:58},{k:"heavyMetalReduction",t:"重金属(t)",w:58},{k:"other",t:"其他",w:80}];
var NUMS=["investment","economicBenefit","electricitySaving","coalSaving","co2Reduction","materialSaving","waterSaving","codcrReduction","ammoniaReduction","smokeReduction","dustReduction","so2Reduction","noxReduction","vocReduction","solidWasteReduction","liquidWasteReduction","heavyMetalReduction"];
function G(id){return document.getElementById(id)}
function toast(m,t){var c=G("tbx");var el=document.createElement("div");el.className="toast "+(t||"info");el.textContent=m;c.appendChild(el);setTimeout(function(){el.style.opacity="0";el.style.transition="opacity .25s";setTimeout(function(){el.remove()},250)},3500)}
function esc(s){return String(s||"")}
(function(){var dz=G("dz");if(!dz)return;dz.onclick=function(){G("fi").click()};G("fi").onchange=function(e){pick(e.target.files[0])};console.log("App init OK")})()

document.addEventListener('DOMContentLoaded',function(){
  var tbd=document.getElementById('tbd');
  if(tbd){
    tbd.addEventListener('click',function(e){
      var td=e.target.closest('td.nc');
      if(!td) return;
      // Find which row and column
      var row=td.parentElement;
      var rows=Array.from(tbd.querySelectorAll('tr'));
      var ri=rows.indexOf(row);
      if(ri<0||ri>=rows.length-1) return; // skip totals row
      var cells=Array.from(row.querySelectorAll('td.nc'));
      var ci=cells.indexOf(td);
      if(ci<0) return;
      // Map ci to field key
      var key=NUMS[ci];
      if(key) trc(ri,key);
    });
  }
});

function pick(f){if(!f)return;F=f;G("fnm").textContent=f.name;G("fsz").textContent=f.size<1048576?(f.size/1024).toFixed(1)+" KB":(f.size/1048576).toFixed(1)+" MB";G("ok").style.display="flex";var b=G("mb");b.textContent="开始提取";b.classList.add("ready")}
function mainBtn(){if(F)start();else G("fi").click()}
function start(){if(!F){toast("请先上传文件");return}var b=G("mb");b.textContent="处理中...";b.disabled=true;G("up").style.display="none";G("prog").style.display="block";G("pe").style.display="none";ps(1,"r");ps(2,"w");ps(3,"w");G("pf").className="pfill w1";G("pt").textContent="正在解析...";var fd=new FormData();fd.append("file",F);fetch("/api/ocr",{method:"POST",body:fd}).then(function(r){return r.json()}).then(function(d){if(!d.ok)throw new Error(d.error);R=d.text;fid=d.fileId||"";ps(1,"d");ps(2,"r");G("pf").className="pfill w2";G("pt").textContent="AI分析中...";return fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:R})})}).then(function(r){return r.json()}).then(function(d){if(!d.ok)throw new Error(d.error);ps(2,"d");ps(3,"r");D=d.data;D.s3=D.section3||{};D.s4=D.section4||{plans:[],totals:{}};render();show();ps(3,"d");G("pf").className="pfill w3";G("pt").textContent="完成!";setTimeout(function(){G("prog").style.display="none";b.textContent="开始提取";b.classList.add("ready");b.disabled=false},600)}).catch(function(e){G("pe").style.display="block";G("pe").textContent="出错:"+e.message;ps(1,"e");ps(2,"e");ps(3,"e");b.textContent="重试";b.classList.add("ready");b.disabled=false;toast("失败:"+e.message,"err")})}
function ps(n,s){var el=G("ps"+n);var dot=el.querySelector(".dot");dot.className="dot "+s;dot.textContent=s==="d"?"V":s==="e"?"X":String(n)}
function show(){G("sp").style.display="flex";G("sb").style.display="block";G("fw").style.display="block";G("tb").textContent=R||"(未提取到文本)";if(fid){G("pdfFrame").src="/uploads/"+fid;G("pdfFrame").style.display="block"}G("tb").classList.add("hide")}
function render(){G("fco").value=D.companyName||"";G("fsu").value=(D.s3||D.section3||{}).projectSummary||(D.section3||{}).projectSummary||"";G("fre").value=(D.s3||D.section3||{}).resultsSummary||(D.section3||{}).resultsSummary||"";G("sc").textContent=D.companyName||"-";G("sn").textContent=(D.s4||D.section4||{}).plans.length;G("si").textContent=(((D.s4||D.section4||{}).totals||{}).investment||0).toFixed(2);var th="<tr>";COLS.forEach(function(c){var cls=c.s===0?" sl":c.s===1?" sl2":"";th+="<th class=\""+cls+"\" style=\"min-width:"+c.w+"px\">"+c.t+"</th>"});th+="<th></th></tr>";G("th").innerHTML=th;rtable()}
function rtable(){var pl=(D.s4||D.section4||{}).plans||[];var t=(D.s4||D.section4||{}).totals||{};var h="";pl.forEach(function(p,i){h+="<tr>";COLS.forEach(function(c){var v=p[c.k]!==undefined?p[c.k]:"";var cls=c.s===0?" sl":c.s===1?" sl2":"";if(NUMS.indexOf(c.k)>=0){var nv=parseFloat(v)||0;h+="<td class=\""+cls+" nc\" onclick=\"trc("+i+",'"+c.k+"')\"><input type=\"number\" step=\"0.01\" value=\""+nv.toFixed(2)+"\" onchange=\"upd("+i+",'"+c.k+"',parseFloat(this.value)||0)\" style=\"width:"+(c.w-8)+"px\"></td>"}else if(c.k==="seq"){h+="<td class=\""+cls+"\"><input type=\"text\" value=\""+esc(String(v))+"\" onchange=\"upd("+i+",'seq',this.value)\" style=\"width:"+(c.w-8)+"px\"></td>"}else if(c.ta){h+="<td class=\""+cls+"\"><textarea onchange=\"upd("+i+",'"+c.k+"',this.value)\" rows=\"1\">"+esc(String(v))+"</textarea></td>"}else{h+="<td class=\""+cls+"\"><input type=\"text\" value=\""+esc(String(v))+"\" onchange=\"upd("+i+",'"+c.k+"',this.value)\"></td>"}});h+="<td><button onclick=\"delP("+i+")\" style=\"border:none;color:#ef4444;cursor:pointer;font-size:14px\">x</button></td></tr>"});h+="<tr class=\"tr\">";COLS.forEach(function(c){var cls=c.s===0?" sl":c.s===1?" sl2":"";if(c.k==="seq")h+="<td class=\""+cls+"\">合计</td>";else if(NUMS.indexOf(c.k)>=0){var tv=parseFloat(t[c.k])||0;h+="<td class=\""+cls+"\"><input type=\"number\" step=\"0.01\" value=\""+tv.toFixed(2)+"\" onchange=\"utot('"+c.k+"',parseFloat(this.value)||0)\" style=\"width:"+(c.w-8)+"px;font-weight:700\" id=\"tot_"+c.k+"\"></td>"}else h+="<td class=\""+cls+"\"></td>"});h+="<td></td></tr>";G("tbd").innerHTML=h}
function sf(p,v){if(!D)return;var ps=p.split(".");var o=D;for(var i=0;i<ps.length-1;i++)o=o[ps[i]]=o[ps[i]]||{};o[ps[ps.length-1]]=v}
function upd(i,k,v){var s4=D.s4||D.section4;if(s4&&s4.plans[i]){s4.plans[i][k]=v;sum()}}
function utot(k,v){var s4=D.s4||D.section4;if(s4){s4.totals=s4.totals||{};s4.totals[k]=v;G("si").textContent=(s4.totals.investment||0).toFixed(2)}}
function sum(){var s4=D.s4||D.section4;if(!s4)return;var t={};NUMS.forEach(function(k){t[k]=s4.plans.reduce(function(s,p){return s+(parseFloat(p[k])||0)},0)});s4.totals=t;NUMS.forEach(function(k){var el=G("tot_"+k);if(el)el.value=t[k].toFixed(2)});G("si").textContent=(t.investment||0).toFixed(2);G("sn").textContent=s4.plans.length}
function addP(){if(!D)D={companyName:"",section3:{projectSummary:"",resultsSummary:""},s4:{plans:[],totals:{}}};var s4=D.s4||D.section4;var m=s4.plans.reduce(function(mx,p){return Math.max(mx,parseInt(String(p.seq).replace(/\D/g,""))||0)},0);s4.plans.push({seq:String(m+1),name:"",content:"",investment:0,economicBenefit:0,electricitySaving:0,coalSaving:0,co2Reduction:0,materialSaving:0,waterSaving:0,codcrReduction:0,ammoniaReduction:0,smokeReduction:0,dustReduction:0,so2Reduction:0,noxReduction:0,vocReduction:0,solidWasteReduction:0,liquidWasteReduction:0,heavyMetalReduction:0,other:""});rtable()}
function delP(i){var s4=D.s4||D.section4;if(s4){s4.plans.splice(i,1);sum();rtable()}}
function openCfg(){G("cfg").classList.add("show")}
function saveCfg(){G("cfg").classList.remove("show");toast("已保存")}
function trc(i,k){if(!R){toast("无原文数据");return}var p=(D.s4||D.section4||{}).plans[i];if(!p){toast("方案不存在");return}var cit=(p.citations||{})[k];var el=G("tb");el.classList.remove("hide");if(cit&&cit.length>2){var pos=R.indexOf(cit);console.log("trc: cite="+cit+" pos="+pos);if(pos>=0){var s=Math.max(0,pos-80);var e=Math.min(R.length,pos+cit.length+300);var html=R.substring(s,e);html=html.split(cit).join("<mark style=\"background:#fef08a;padding:1px 3px;border-radius:2px\">"+cit+"</mark>");el.innerHTML="<div style=\"background:#fffbeb;padding:4px 10px;font-size:11px;color:#92400e;margin-bottom:8px\">AI引用: "+cit.substring(0,80)+"</div><pre style=\"white-space:pre-wrap;font-size:12px;line-height:1.7;margin:0\">"+html+"</pre>";var m=el.querySelector("mark");if(m)m.scrollIntoView({behavior:"smooth",block:"center"});return}}var nm=p.name||"";if(!nm){toast("方案无名");return}var pp=R.indexOf(nm);console.log("trc: name="+nm+" pos="+pp);if(pp<0){toast("未找到方案出处");return}var s=Math.max(0,pp-200);var e=Math.min(R.length,pp+2500);var html=R.substring(s,e);var v=p[k];if(v&&!isNaN(parseFloat(v))){var vs=String(parseFloat(v));var vs2=parseFloat(v).toFixed(2);html=html.split(vs).join("<mark style=\"background:#fef08a;padding:1px 3px;border-radius:2px\">"+vs+"</mark>");if(vs!==vs2)html=html.split(vs2).join("<mark style=\"background:#fef08a;padding:1px 3px;border-radius:2px\">"+vs2+"</mark>")}html=html.split(nm).join("<mark style=\"background:#bfdbfe;padding:1px 3px;border-radius:2px\">"+nm+"</mark>");el.innerHTML="<div style=\"background:#fffbeb;padding:4px 10px;font-size:11px;color:#92400e;margin-bottom:8px\">方案: "+nm+" (数值:"+(v||0)+")</div><pre style=\"white-space:pre-wrap;font-size:12px;line-height:1.7;margin:0\">"+html+"</pre>";var m=el.querySelector("mark");if(m)m.scrollIntoView({behavior:"smooth",block:"center"})}
function csvE(s){s=String(s||"");if(s.indexOf(",")>=0||s.indexOf("\n")>=0){var q=String.fromCharCode(34);return q+s.split(q).join(q+q)+q}return s}
function doWord(){if(!D){toast("无数据");return}fetch("/api/export-word",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data:D})}).then(function(r){return r.blob()}).then(function(b){var a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(D.companyName||"")+"资金申报材料.doc";a.click()}).catch(function(e){toast("导出失败:"+e.message,"err")})}
function xCSV(){if(!D||!D.s4&&!D.section4){toast("无数据");return}var s4=D.s4||D.section4;var csv="企业名称,"+csvE(D.companyName)+"\n方案总数,"+s4.plans.length+"\n";csv+="序号,项目名称,项目内容,投资额(万元),经济效益(万元),节电(万kWh),折标煤(t),CO2(t),原辅料(t),节水(t),COD(t),氨氮(t),烟尘(t),粉尘(t),SO2(t),NOx(t),VOC(t),固废(t),废液(t),重金属(t),其他\n";s4.plans.forEach(function(p){csv+=[p.seq||"",csvE(p.name),csvE(p.content)].concat(NUMS.map(function(k){return(parseFloat(p[k])||0).toFixed(2)})).concat([csvE(p.other)]).join(",")+"\n"});var b=new Blob([csv],{type:"text/csv;charset=utf-8"});var a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(D.companyName||"")+"资金申报材料.csv";a.click();toast("已下载")}
function demo(){D={companyName:"测试公司",section3:{projectSummary:"WD1-锅炉余热回收:对燃煤锅炉进行余热回收改造。",resultsSummary:"年节约标煤2016吨。"},s4:{plans:[{seq:"WD1",name:"锅炉余热回收利用",content:"余热回收改造",investment:320.50,economicBenefit:85,electricitySaving:0,coalSaving:850,co2Reduction:2200,materialSaving:0,waterSaving:0,codcrReduction:0,ammoniaReduction:0,smokeReduction:12,dustReduction:0,so2Reduction:12,noxReduction:0,vocReduction:0,solidWasteReduction:0,liquidWasteReduction:0,heavyMetalReduction:0,other:"",citations:{investment:"投资320.50万元",coalSaving:"标煤850吨",co2Reduction:"CO2减排2200吨"}},{seq:"ZG1",name:"废水处理回用",content:"MBR+RO系统",investment:580.00,economicBenefit:120,electricitySaving:0,coalSaving:0,co2Reduction:0,materialSaving:0,waterSaving:180000,codcrReduction:45,ammoniaReduction:3.2,smokeReduction:0,dustReduction:0,so2Reduction:0,noxReduction:0,vocReduction:0,solidWasteReduction:0,liquidWasteReduction:0,heavyMetalReduction:0,other:""}],totals:{investment:900.50,economicBenefit:205,electricitySaving:0,coalSaving:850,co2Reduction:2200,materialSaving:0,waterSaving:180000,codcrReduction:45,ammoniaReduction:3.2,smokeReduction:12,dustReduction:0,so2Reduction:12,noxReduction:0,vocReduction:0,solidWasteReduction:0,liquidWasteReduction:0,heavyMetalReduction:0}}};R="锅炉余热回收利用：对燃煤锅炉进行余热回收改造，投资320.50万元，年节约标煤850吨，CO2减排2200吨，SO2减排12吨。\n废水处理回用：建设MBR+RO深度处理系统，投资580万元，年节水18万吨，COD减排45吨。";render();G("up").style.display="none";G("sp").style.display="flex";G("sb").style.display="block";G("fw").style.display="block";G("tb").textContent=R;G("tb").classList.add("hide");G("pdfFrame").style.display="none";toast("已加载示例,点表格数值查看溯源")}
function reset(){F=null;D=null;R="";fid=null;G("sp").style.display="none";G("prog").style.display="none";G("up").style.display="flex";G("ok").style.display="none";var b=G("mb");b.textContent="选择文件";b.classList.remove("ready")}
function showTab(t){if(t==="pdf"){if(fid){G("pdfFrame").src="/uploads/"+fid}G("pdfFrame").style.display="block";G("tb").classList.add("hide")}else{G("pdfFrame").style.display="none";G("tb").classList.remove("hide")}}
